.F...
======================================================================
FAIL: test_invalid (__main__.TestCountLarge)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a1/marking_scripts/test_helpers.py", line 193, in _t
    self.assertEqual(returncode, expected_status)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 5 tests in 0.290s

FAILED (failures=1)
