.....F..
======================================================================
FAIL: test_cmdline_pid_and_d_valid (__main__.TestCommandline)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a2/marking_scripts/test_helpers.py", line 193, in _t
    self.assertEqual(returncode, expected_status)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 8 tests in 0.258s

FAILED (failures=1)
